// This file groups together miscellaneous functions used throughout in our project

/*
	All the below remove<someErrorMessage>() functions are utility
	functions which are used to remove errors which are generated by
	invalid form submissions
*/

function removeUserErrorMessage(ref) {
	var userNameError = document.getElementById("userNameError");
	ref.style.borderColor = "";
	userNameError.innerHTML = "";
}

function removePasswordErrorMessage(ref) {
	var passwordError = document.getElementById("passwordError")
	ref.style.borderColor = "";
	passwordError.innerHTML = "";
}

function removeFirstNameErrorMessage(ref) {
	var firstNameError = document.getElementById("firstNameError");
	var emptyFormError = document.getElementById("emptyFormError");
	ref.style.borderColor = "";
	firstNameError.innerHTML = "";
	emptyFormError.innerHTML = "";
}

function removeLastNameErrorMessage(ref) {
	var lastNameError = document.getElementById("lastNameError");
	ref.style.borderColor = "";
	lastNameError.innerHTML = "";
}

function removeGenderErrorMessage(ref) {
	var genderError = document.getElementById("genderError");
	ref.style.borderColor = "";
	genderError.innerHTML = "";
}

function removeEmailErrorMessage(ref) {
	var emailError = document.getElementById("emailError");
	ref.style.borderColor = "";
	emailError.innerHTML = "";
}

function removeRetypeErrorMessage(ref) {
	var firstNameError = document.getElementById("retypePasswordError");
	ref.style.borderColor = "";
	retypePasswordError.innerHTML = "";
}

function removeTitleErrorMessage(ref) {
	var titleError = document.getElementById("titleError");
	ref.style.borderColor = "";
	titleError.innerHTML = "";
}

function removeDescriptionErrorMessage(ref) {
	var descriptionError = document.getElementById("descriptionError");
	ref.style.borderColor = "";
	descriptionError.innerHTML = "";
}

function removeCollegeErrorMessage(ref) {
	var collegeError = document.getElementById("collegeError");
	ref.style.borderColor = "";
	collegeError.innerHTML = "";
}

function removeAddressErrorMessage(ref) {
	var addressError = document.getElementById("addressError");
	ref.style.borderColor = "";
	addressError.innerHTML = "";
}

function removeContactErrorMessage(ref) {
	var contactError = document.getElementById("contactError");
	ref.style.borderColor = "";
	contactError.innerHTML = "";
}

function removeEmailErrorMessage(ref) {
	var emailError = document.getElementById("emailError");
	ref.style.borderColor = "";
	emailError.innerHTML = "";
}

function removeAmountErrorMessage(ref) {
	var amountError = document.getElementById("amountError");
	ref.style.borderColor = "";
	amountError.innerHTML = "";
}

// Parses the amountText which is of the form: 'Amount paid: 150Rs'
function parseAmount(amountText) {
	var amount = "";
	for(var i = 13;amountText[i] !== 'R';i++)
		amount += amountText[i];
	return amount;
}

// Opens the editing section in profile.html
function openEditingSection() {
	// Get the modal
	var modal = document.getElementById('myModal');
	modal.style.display = "block";
	return false;
}

// Updates the college field in the database
function updateCollege(userName,college) {
	// We perform an AJAX POST operation to the database by the following php script
	$.post('php/updateCollege.php',
			{ 	userName: userName,
				college: college
			},
			function(data){
			    console.log(data);
			}
	);
}

// Updates the address field in the database
function updateAddress(userName,address) {
	// We perform an AJAX POST operation to the database by the following php script
	$.post('php/updateAddress.php',
			{ 	userName: userName,
				address: address
			},
			function(data){
			    console.log(data);
			}
	);
}

// Updates the contact field in the database
function updateContact(userName,contact) {
	// We perform an AJAX POST operation to the database by the following php script
	$.post('php/updateContact.php',
			{ 	userName: userName,
				contact: contact
			},
			function(data){
			    console.log(data);
			}
	);
}

// Updates the email field in the database
function updateEmail(userName,email) {
	// We perform an AJAX POST operation to the database by the following php script
	$.post('php/updateEmail.php',
			{ 	userName: userName,
				email: email
			},
			function(data){
			    console.log(data);
			}
	);
}

function forward_to_signup() {
	window.location.href = SIGN_UP_URL;
	// We return false so that action attribute of the corresponding form tag doesn't get executed
	// when onSubmit returns false
	return false;
}