// This file groups together miscellaneous functions used throughout in our project

/*
	All the below remove<someErrorMessage>() functions are utility
	functions which are used to remove errors which are generated by
	invalid form submissions
*/

function removeUserErrorMessage(ref) {
	var userNameError = document.getElementById("userNameError");
	ref.style.borderColor = "";
	userNameError.innerHTML = "";
}

function removePasswordErrorMessage(ref) {
	var passwordError = document.getElementById("passwordError")
	ref.style.borderColor = "";
	passwordError.innerHTML = "";
}

function removeFirstNameErrorMessage(ref) {
	var firstNameError = document.getElementById("firstNameError");
	var emptyFormError = document.getElementById("emptyFormError");
	ref.style.borderColor = "";
	firstNameError.innerHTML = "";
	emptyFormError.innerHTML = "";
}

function removeLastNameErrorMessage(ref) {
	var lastNameError = document.getElementById("lastNameError");
	ref.style.borderColor = "";
	lastNameError.innerHTML = "";
}

function removeGenderErrorMessage(ref) {
	var genderError = document.getElementById("genderError");
	ref.style.borderColor = "";
	genderError.innerHTML = "";
}

function removeEmailErrorMessage(ref) {
	var emailError = document.getElementById("emailError");
	ref.style.borderColor = "";
	emailError.innerHTML = "";
}

function removeRetypeErrorMessage(ref) {
	var firstNameError = document.getElementById("retypePasswordError");
	ref.style.borderColor = "";
	retypePasswordError.innerHTML = "";
}

function forward_to_signup() {
	window.location.href = SIGN_UP_URL;
}