// This file groups together miscellaneous functions used throughout in our project

/*
	All the below remove<someErrorMessage>() functions are utility
	functions which are used to remove errors which are generated by
	invalid form submissions
*/

function removeUserErrorMessage(ref) {
	var userNameError = document.getElementById("userNameError");
	ref.style.borderColor = "";
	userNameError.innerHTML = "";
}

function removePasswordErrorMessage(ref) {
	var passwordError = document.getElementById("passwordError")
	ref.style.borderColor = "";
	passwordError.innerHTML = "";
}

function removeFirstNameErrorMessage(ref) {
	var firstNameError = document.getElementById("firstNameError");
	var emptyFormError = document.getElementById("emptyFormError");
	ref.style.borderColor = "";
	firstNameError.innerHTML = "";
	emptyFormError.innerHTML = "";
}

function removeLastNameErrorMessage(ref) {
	var lastNameError = document.getElementById("lastNameError");
	ref.style.borderColor = "";
	lastNameError.innerHTML = "";
}

function removeGenderErrorMessage(ref) {
	var genderError = document.getElementById("genderError");
	ref.style.borderColor = "";
	genderError.innerHTML = "";
}

function removeEmailErrorMessage(ref) {
	var emailError = document.getElementById("emailError");
	ref.style.borderColor = "";
	emailError.innerHTML = "";
}

function removeRetypeErrorMessage(ref) {
	var firstNameError = document.getElementById("retypePasswordError");
	ref.style.borderColor = "";
	retypePasswordError.innerHTML = "";
}

function forward_to_signup() {
	window.location.href = SIGN_UP_URL;
	// We return false so that action attribute of the corresponding form tag doesn't get executed
	// when onSubmit returns false
	return false;
}

function removeTitleErrorMessage(ref) {
	var titleError = document.getElementById("titleError");
	ref.style.borderColor = "";
	titleError.innerHTML = "";
}

function removeDescriptionErrorMessage(ref) {
	var descriptionError = document.getElementById("descriptionError");
	ref.style.borderColor = "";
	descriptionError.innerHTML = "";
}

function removeCollegeErrorMessage(ref) {
	var collegeError = document.getElementById("collegeError");
	ref.style.borderColor = "";
	collegeError.innerHTML = "";
}

function removeAddressErrorMessage(ref) {
	var addressError = document.getElementById("addressError");
	ref.style.borderColor = "";
	addressError.innerHTML = "";
}

function removeContactErrorMessage(ref) {
	var contactError = document.getElementById("contactError");
	ref.style.borderColor = "";
	contactError.innerHTML = "";
}

function removeEmailErrorMessage(ref) {
	var emailError = document.getElementById("emailError");
	ref.style.borderColor = "";
	emailError.innerHTML = "";
}

function removeAmountErrorMessage(ref) {
	var amountError = document.getElementById("amountError");
	ref.style.borderColor = "";
	amountError.innerHTML = "";
}

// Parses the amountText which is of the form: 'Amount paid: 150Rs'
function parseAmount(amountText) {
	var amount = "";
	for(var i = 13;amountText[i] !== 'R';i++)
		amount += amountText[i];
	return amount;
}